image:
  file: .gitpod.Dockerfile
experimentalNetwork: true

# ddev and composer are running as part of the prebuild
# when starting a workspace all docker images are ready
tasks:
  - name: Terminal
    init: |
      export DDEV_NONINTERACTIVE=true
      .ddev/gitpod-setup-ddev.sh
      ddev composer install
      ddev drush si -y --account-pass=admin --site-name='ddev_gitpod' demo_umami
    command: |
      .ddev/gitpod-setup-ddev.sh
      ddev composer install
      gp await-port 8080 && gp preview $(gp url 8080)

# VScode xdebug extension
vscode:
  extensions:
    - felixfbecker.php-debug
    - bmewburn.vscode-intelephense-client
    - ziyasal.vscode-open-in-github

ports:
  # Used by projector
  - port: 6942
    onOpen: ignore
    visibility: private
  # Direct-connect ddev-webserver port that is the main port
  - port: 8080
    onOpen: ignore
    visibility: private
  # Currently un-notified and unsupported mailhog http port
  - port: 8025
    onOpen: ignore
    visibility: private
  # Currently un-notified and unsupported mailhog https port
  - port: 8026
    onOpen: ignore
    visibility: private
  # Currently un-notified and unsupported phpmyadmin http port
  - port: 8036
    onOpen: ignore
    visibility: private
  # Currently un-notified and unsupported phpmyadmin https port
  - port: 8037
    onOpen: ignore
    visibility: private
  # router http port that we're ignoring.
  - port: 8888
    onOpen: ignore
    visibility: private
  # router https port that we're ignoring.
  - port: 8889
    onOpen: ignore
    visibility: private
  # xdebug port
  - port: 9000
    onOpen: ignore
    visibility: private
  # projector port
  - port: 9999
    visibility: private

github:
  prebuilds:
    # enable for the master/default branch (defaults to true)
    master: true
    # enable for all branches in this repo (defaults to false)
    branches: true
    # enable for pull requests coming from this repo (defaults to true)
    pullRequests: true
    # enable for pull requests coming from forks (defaults to false)
    pullRequestsFromForks: true
    # add a check to pull requests (defaults to true)
    addCheck: true
    # add a "Review in Gitpod" button as a comment to pull requests (defaults to false)
    addComment: true
    # add a "Review in Gitpod" button to the pull request's description (defaults to false)
    addBadge: true
    # add a label once the prebuild is ready to pull requests (defaults to false)
    addLabel: true
