image:
  file: .gitpod.Dockerfile

# ddev and composer are running as part of the prebuild
# when workspace gets loaded all docker images are ready
tasks:
  - prebuild: composer install
  # - prebuild: sudo docker-up &
  # # Wait for docker to come up before running ddev
  # - prebuild: |
  #     brew upgrade ddev
  #     mkcert -install
  #     # Wait for docker to come up before doing gitpod setup (gitpod-setup requires docker)
  #     while ! docker ps 2>/dev/null; do
  #       sleep 1
  #     done
  #     .ddev/gitpod-setup-ddev.sh

  # Running composer install, docker-up, and start ddev
  # - name: composer
  #   command: composer install
  # - name: docker-up
  #   openMode: split-right
  #   command: sudo docker-up
  # - name: ddev_run
  #   openIn: left
  #   command: |
  #     brew upgrade ddev
  #     mkcert -install
  #     # Wait for docker to come up before doing gitpod setup (gitpod-setup requires docker)
  #     while ! docker ps 2>/dev/null; do
  #       sleep 1
  #     done
  #     .ddev/gitpod-setup-ddev.sh


# Set the following ports public
ports:
  - port: 6942
    onOpen: ignore
  - port: 8080
  - port: 8025
    onOpen: ignore
  - port: 8026
    onOpen: ignore
  - port: 8036
    onOpen: ignore
  - port: 8037
    onOpen: ignore
  - port: 8443
    onOpen: ignore
  - port: 9999

github:
  prebuilds:
    # enable for the master/default branch (defaults to true)
    master: true
    # enable for all branches in this repo (defaults to false)
    branches: true
    # enable for pull requests coming from this repo (defaults to true)
    pullRequests: true
    # enable for pull requests coming from forks (defaults to false)
    pullRequestsFromForks: true
    # add a check to pull requests (defaults to true)
    addCheck: true
    # add a "Review in Gitpod" button as a comment to pull requests (defaults to false)
    addComment: true
    # add a "Review in Gitpod" button to the pull request's description (defaults to false)
    addBadge: true
    # add a label once the prebuild is ready to pull requests (defaults to false)
    addLabel: true
