image:
  file: .gitpod.Dockerfile

# Use 'lock file' to delay running ddev until it is installed
# https://www.gitpod.io/blog/gitpodify/#running-init-scripts
tasks:
  # - name: ddev_install
  #   init: |
  #     touch /tmp/.ddev-lock
  #     brew tap drud/ddev && brew install ddev
  #     rm /tmp/.ddev-lock
  - init: composer install
  - name: docker_up
    command: sudo docker-up
  - name: ddev_run
    # init: sleep 1 && while [ -f /tmp/.ddev-lock ]; do sleep 1; done
    command: |
      sleep 5
      docker rm -f $(docker ps -aq) || true
      docker rmi -f $(docker images -q) || true
      mkcert -install
      ddev config global --instrumentation-opt-in=true --router-bind-all-interfaces=true --router-http-port=8080 --router-https-port=8443 --use-dns-when-possible=false
      .ddev/generate-fqdns.sh
      .ddev/generate-xdebug-host-ip.sh
      ddev start

# Make the following ports public
ports:
  - port: 8080
  - port: 8025
    onOpen: ignore
  - port: 8026
    onOpen: ignore
  - port: 8036
    onOpen: ignore
  - port: 8037
    onOpen: ignore
  - port: 8443
    onOpen: ignore

github:
  prebuilds:
    # enable for the master/default branch (defaults to true)
    master: true
    # enable for all branches in this repo (defaults to false)
    branches: true
    # enable for pull requests coming from this repo (defaults to true)
    pullRequests: true
    # enable for pull requests coming from forks (defaults to false)
    pullRequestsFromForks: true
    # add a check to pull requests (defaults to true)
    addCheck: true
    # add a "Review in Gitpod" button as a comment to pull requests (defaults to false)
    addComment: true
    # add a "Review in Gitpod" button to the pull request's description (defaults to false)
    addBadge: true
    # add a label once the prebuild is ready to pull requests (defaults to false)
    addLabel: true
